### ISSUE TITLE
How to remove a 'Team Profile'

### ISSUE THREAD

**Issue by Bluesguy1984** [TonCunha/multi-microsoft-teams#1]
Great tool.  Easy to use.

I need to remove one of my Teams from the profile.  How do I do that?

**Comment by TonCunha** [comment]
Hi, just select the desired profile and press delete key.
Thanks.

**Comment by bnk-ooz** [comment]
Complements for your great tool. I use it every day.

I run into one problem: when a invitation for a meeting is send by email, MMS often picks the wrong account.
How do I manage MMS to pick the right team when starting a meeting via an email link?
