### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by aldussa** [TonCunha/multi-microsoft-teams#10]
Hi, 

Love the app - I'm a MSFT Trainer and been great to use the app in order to showcase the Breakout Rooms function. 

However, upon starting Multi MS Teams I've come accross this error every time I want to start a new profile (see screenshot). 

Was hoping you could maybe point out what may cause this issue. 

Thanks in advance!
![Capture](https://user-images.githubusercontent.com/82172793/114074009-eb386480-9871-11eb-8f5b-50d9237b212e.PNG)

Alex

**Comment by TonCunha** [comment]
Hi @aldussa,
I've never seen this error, but let's try something.

Access the folder:
C:\Users\MODAdministrator\AppData\Local\Microsoft\Teams\

1) Is there a "current" folder?
If that folder does not exist, update Microsoft Teams.

2) Is there a "download" folder inside the "current" folder?
If not, try to create and run Multi Teams.

3) Is there a "download" folder outside the "current" folder?
If not, try to create and run Multi Teams.

4) Finally, if it still didn't work
Close Multi Teams and Microsoft Teams. 
Access the "CustomProfiles" folder and delete profile folder

**Comment by aldussa** [comment]
Thank you for the fast reply! 

Just wanted to follow up with you - unfortunately none of the above options worked (must of been something on my end that disrupted the Multi MS Teams app). 

So ended up, uninstalling Teams, Removed all traces of it in the C: drive and reinstalled it and it finally worked!

Thanks again! Keep up the great work!

Alex

**Comment by nsymms** [comment]
I just hit this exact problem this morning. Teams updated overnight and now I get the above error.

Tried creating directories, uninstall / reinstall -- still the same problem. It has something to do with the squirrel updater. Looks like Teams uses a custom version.

When I get more time I'll look at it more closely.
***
Edit 5/8/2021:
Found the problem. I really should have tried more variations on the original suggestion. I went the hardcore route, monitoring the registry and file system calls as Teams started up by itself (success) versus starting via Multi-Teams (fail).

### Short answer:
Teams.exe is looking for your `Downloads` folder and can't find one for the custom profiles.

### "The fix" for anyone who stumbles on this via some search engine:
1. Navigate to the directory for your custom multi-ms-teams profile which should be something like `C:\Users\#username#\AppData\Local\Microsoft\Teams\CustomProfiles\#your-multi-teams-profile#\`
2. Create a "Downloads" folder there.
3. Enjoy
