### ISSUE TITLE
Difference profile but got same MS Teams

### ISSUE THREAD

**Issue by et-non** [TonCunha/multi-microsoft-teams#12]
Hi,

My Laptop working fine no problem with Multi MS Teams but My Office Desktop when I click difference profile. I got same MS Teams.

My Laptop 
MS Teams version : 1.4.00.11161
Multi MS Teams: 1.0.0.4
Office Desktop
MS Teams version : 1.4.00.11161
Multi MS Teams: 1.0.0.4

**Comment by TonCunha** [comment]
Hi,

Try deleting all profiles and follow these steps.

1. Open your Microsoft Teams without MS Teams
2. Click in your picture
3. Open Settings
4. Uncheck Auto-start application
5. Close Microsoft Teams via tray icon
6. Start MS Teams
7. Create your profiles
8. Select a profile and Launch Teams
9. Uncheck the options auto-start application in all Microsoft Teams (like steps 2, 3 and 4)
10. You can check Auto Start option to launch all profiles when Windows starts

**Comment by et-non** [comment]
Hi,

I follow step above but still got the same problem.

**Comment by TonCunha** [comment]
Hi @et-non
Have you made any progress with your problem?
If yes, could you share with us?

**Comment by et-non** [comment]
Hi @TonCunha 
I still have the same problem, couldn't fix it yet.

**Comment by TonCunha** [comment]
Hi @et-non 
We release a new version (1.0.0.5). Could you please update, recreate the profiles, and verify if your problem are fixed?
Thanks

**Comment by et-non** [comment]
Hi @TonCunha ,

Sorry for late reply.
Still got same problem.

Thank you,
