### ISSUE TITLE
unable to delete profile

### ISSUE THREAD

**Issue by tradosh** [TonCunha/multi-microsoft-teams#17]
version 1.0.5
when trying to delete a profile getting the error: Profile x has not been deleted. Close Microsoft Teams and try again.

however, this is on the just booted system where teams haven't launched yet, checked task manager there are no teams instances there either.

**Comment by TonCunha** [comment]
Probably some process is using the files from the Microsoft Teams profile folder. I'll mark it as a bug and check for some improvement for the next version.

**Comment by wterbeek** [comment]
Had the same issue. when I checked where the profiles are stored, I manually tried to remove the profile. This failed because 4 files were in use by Outlook. After I shutdown outlook, I could remove the entire folder for the profile I wanted to delete
