### ISSUE TITLE
Losing connection issues after a while

### ISSUE THREAD

**Issue by Devvox93** [TonCunha/multi-microsoft-teams#18]
First of all, thank you for this app! I've been trying to work with Edge Progressive Web Apps, but that has limitations (like no backgrounds/blur with video and only 1 additional profile at a time.

On to the issue:
After a while of running multiple instances, a grey bar at the top saying "We weren't able to connect. Sign in and we'll try again. Sign in" is displayed.
When clicking the "Sign in" link, it tries to reconnect, but fails after a short while.
In the meantime, the Calendar and people's status icons are not updated.

I'm not sure if this can be fixed or prevented by the Multi Teams app, but thought I'd report it nonetheless.
Workaround is to manually sign out and sign in again or closing and reopening the instance/profile.

**Comment by TonCunha** [comment]
Thanks @Devvox93
This is Microsoft Teams behavior and MMT cannot handle it.
