### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by SiegfriedBaldauf** [TonCunha/multi-microsoft-teams#19]
How can I stop the autostart option of Multi.MS.Teams? After enabling it setting are mo longer available.

**Comment by Ztarbox** [comment]
Don't know what you mean by "no longer available", but Autostart is done by adding en entry in registry.
So start "regedit".
Navigate to "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run"
Delete the string value "Multi MS Teams"
Done

**Comment by SiegfriedBaldauf** [comment]
Hi TonChua,

The Problem is that the UI of "Multi MS Teams.exe" is no longer available. It starts both Teams instances, but I can not change anything, eg. add a third tenant.
"Multi MS Teams" is not part of the Autostart folder.

Mit freundlichen Grüßen | Yours sincerely

Siegfried

Von: Ztarbox ***@***.***>
Gesendet: Dienstag, 22. März 2022 08:43
An: TonCunha/multi-microsoft-teams ***@***.***>
Cc: Siegfried Baldauf ***@***.***>; Author ***@***.***>
Betreff: Re: [TonCunha/multi-microsoft-teams] Autostart (Issue #19)


Don't know what you mean by "no longer available", but Autostart is done by adding en entry in registry.
So start "regedit".
Navigate to "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run"
Delete the string value "Multi MS Teams"
Done

**Comment by Ztarbox** [comment]
Did you check your taskbar?
MMT starts minimized in Taskbar on AutoStart.

**Comment by SiegfriedBaldauf** [comment]
Thanks a lot - not sure how I finally fixed it, but you got me on the right track.

Mit freundlichen Grüßen | Yours sincerely

Siegfried Baldauf
diplom.designer.(fh)

phone. +49.(0)821.3433561
fax. +49.(0)821.3433562
mobil. +49.(0)172.9915672
***@***.***

BALDAUF PRODUKTDESIGN
fritz-krug-weg.5c
86316.friedberg
www.produkt-designer.com

inhaber: siegfried baldauf | ust-id: de201855578 | Gerichtsstand Augsburg
________________________________
Von: Ztarbox ***@***.***>
Gesendet: Wednesday, April 6, 2022 2:25:14 PM
An: TonCunha/multi-microsoft-teams ***@***.***>
Cc: Siegfried Baldauf ***@***.***>; Author ***@***.***>
Betreff: Re: [TonCunha/multi-microsoft-teams] Autostart (Issue #19)


Did you check your taskbar?
MMT starts minimized in Taskbar on AutoStart.

**Comment by SiegfriedBaldauf** [comment]
Fixed

I checked all twice and searched in the registry editor for all entities of “Multi MS Teams” and deleted them.
Although there was no entry via Task-Manager in the Autorun section, I finally found one in the registry. After deleting everything works fine now.
Thank you for your great small program.

Mit freundlichen Grüßen | Yours sincerely

Siegfried

Von: Ztarbox ***@***.***>
Gesendet: Dienstag, 22. März 2022 08:43
An: TonCunha/multi-microsoft-teams ***@***.***>
Cc: Siegfried Baldauf ***@***.***>; Author ***@***.***>
Betreff: Re: [TonCunha/multi-microsoft-teams] Autostart (Issue #19)


Don't know what you mean by "no longer available", but Autostart is done by adding en entry in registry.
So start "regedit".
Navigate to "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run"
Delete the string value "Multi MS Teams"
Done
