### ISSUE TITLE
Feature Request: Toggle Option

### ISSUE THREAD

**Issue by FabianBeiner** [TonCunha/multi-microsoft-teams#2]
Hi @TonCunha,

As you know: I love your tool! It really makes my daily work easier. Thank you very much! :)

Something I would love to see is the possibility to toggle between activated and deactivated profiles.

So, for example, I might want to open Team 1 + 2, but not 3 for now because 3 is a project on hold. I know I could delete it, but it is perfectly set up and so on.

Thanks for considering.

**Comment by TonCunha** [comment]
Hi @FabianBeiner 
Cool, I'll add this feature.

Thanks for feedback.

**Comment by TonCunha** [comment]
Hi @FabianBeiner
Can you test this version with disable feature?

To disable a profile, double click on the name.

Thanks.
[Multi.MS.Teams.zip](https://github.com/TonCunha/multi-microsoft-teams/files/5638750/Multi.MS.Teams.zip)

**Comment by FabianBeiner** [comment]
Hey @TonCunha,

Thanks so much for doing this! 

I gave it a try, but I get the following error message, even though there are no Teams instances running:

![image](https://user-images.githubusercontent.com/86269/101139407-cc9b3600-3611-11eb-904e-23b9e1bc66b2.png)

**Comment by TonCunha** [comment]
Hi @FabianBeiner, thanks for the feedback.

Let's try a few things.
1- As our program changes the name of the profile folder, try to run Multi MS Teams as administrator and disable a profile.
2- If the message persists, try to disable the profile manually and reload the Multi MS Teams.
To disable, add "[Disabled]" at the beginning of the profile name. Example: "[Disabled] ProfileName".
Profiles folder: C:\Users\YOURUSER\AppData\Local\Microsoft\Teams\CustomProfiles

**Comment by FabianBeiner** [comment]
Hey @TonCunha,

I now know why this didn't work in the first place: Outlook is locking that folder as well. So, you have to not only close Teams, but also Outlook. If this is done, it works like a charm.

Maybe there is a solution to disable the profile without renaming the Profile folder? Otherwise, maybe just change the error notification and you're good to go. 👍

**Comment by FabianBeiner** [comment]
Hey @TonCunha,

Sadly, one issue occurs: In my case, Outlook decided to use its Team Add In from the Teams instance that is now deactivated. That means, the possibility to create a Teams Meeting in Outlook doesn't work anymore, since it is looking for the .dll in the non-existing part anymore. :(

**Comment by TonCunha** [comment]
Hello @FabianBeiner
Thanks for the feedback.

Activate the profile again and return to the latest version. I will find another way to disable profiles.

**Comment by TonCunha** [comment]
Hey @FabianBeiner,
I've been very busy these days, but I've finished adjusting the feature.

Could you test again, please?
Thanks.
[Multi.MS.Teams.zip](https://github.com/TonCunha/multi-microsoft-teams/files/5691161/Multi.MS.Teams.zip)

**Comment by FabianBeiner** [comment]
@TonCunha: I just gave it a try, and it looks like it's working as a charm. :) I randomly enabled and disabled profiles, restarted Outlook, Teams, etc. — and everything worked.

Thank you so much!
