### ISSUE TITLE
Remove default profile / switch default

### ISSUE THREAD

**Issue by sqet** [TonCunha/multi-microsoft-teams#20]
Hello,

Is there any option to remove / switch and then remove default profile in the MMT?

Cheers

**Comment by TonCunha** [comment]
Hi @sqet
Yes, select the profile and press the delete key to open the confirmation box.

Thanks.

**Comment by sqet** [comment]
@TonCunha 
Delete does not work on the default profile

**Comment by TonCunha** [comment]
@sqet 
The default profile cannot be deleted, it is the main one for Microsoft Teams and is used to create other profiles.
