### ISSUE TITLE
Multi MS Teams throw error on every profile, "The system cannot find file specified"

### ISSUE THREAD

**Issue by Uncanny5180** [TonCunha/multi-microsoft-teams#21]
Downloaded the newest release, and .netcore 3.1.24 desktop was installed when I started playing with this.

**Comment by TonCunha** [comment]
Hi @Uncanny5180 

Try doing the following:
- Go to "C:\Users\YOURUSER\AppData\Local\Microsoft\Teams\CustomProfiles" folder and delete all profiles.
- Open "Microsoft Teams" without using "Multi Microsoft Teams" and connect using an account.
- Close "Microsoft Teams"
- Open "Multi Microsoft Teams"
- Create some custom profile and try to connect

**Comment by Uncanny5180** [comment]
Same result. This is in 1.0.0.5. I tried 1.0.0.4 just for fun, and while I dont get the 'cannot find file' error, it doesn't actually do anything when you try to launch the profile. Windows 11 pro on a domain.

**Comment by TonCunha** [comment]
Closed, because it is not possible to repro the bug.
