### ISSUE TITLE
Invites sent from Ouffice 365 always use default account

### ISSUE THREAD

**Issue by DeaneMTuck** [TonCunha/multi-microsoft-teams#24]
Environment:  Win11, Multiple Office365 environments (3)

Functionality (Chat, calls, claendar view, etc all work as expected except that any meeting invite sent from Outlook irrespective of the calendar used always defaults to the default outlook email account.  Invites sent from within teams are correct.

I have reinstalled this app a number of times and it still faults

thanks, Deane

**Comment by TonCunha** [comment]
Sorry @DeaneMTuck, but this is a Microsoft Teams limitation. It doesn't natively support multiple instances, so every external call it always uses the default profile, even using Multi MS Teams.
