### ISSUE TITLE
How to uninstall/remove?

### ISSUE THREAD

**Issue by RyanWor** [TonCunha/multi-microsoft-teams#28]
How does one go about fully removing/uninstalling this and deleting all the extra profiles that were created? I found how to disable them (which required clicking on the tray icon to get the menu up, this was not very well documented or intuitive fwiw). However the Multi MS Teams itself still seems to run at startup and is not listed in the Startup section of Task Manager. Thanks!

**Comment by TonCunha** [comment]
Hi @RyanWor 

Multi MS Teams runs without being installed, so there is no uninstaller. To remove the files, follow the steps:

1- Close all Microsoft Teams instances.
2- Close Multi MS Teams.
3- Delete the Multi MS Teams executable folder.
4- Access the path "C:\Users\YOURUSER\AppData\Local\Microsoft\Teams"
5- Delete the "CustomProfiles" folder (this is safe, this folder was created by Multi MS Teams).

Thanks.

**Comment by RyanWor** [comment]
Thanks @TonCunha that is what I needed. In case anyone else is wondering in the future, the executable is wherever it was originally downloaded to, for me it was in my Downloads folder. And just FYI @TonCunha no complaints about the functionality of Multi Teams itself. It worked great, just my company and my client both have turned off access to Teams from non-company issued devices is the only reason I am no longer using it. Thanks for your work on this project!
