### ISSUE TITLE
How to remove profile?

### ISSUE THREAD

**Issue by PeterGeelen** [TonCunha/multi-microsoft-teams#29]
I found the option to disable the profile (by double click on the MS Multi Teams profile)...

But how can we remove a profile?
There is no right click option on the profiles to remove it.

rgds,
Peter

**Comment by TonCunha** [comment]
Hi @PeterGeelen 
To delete a profile, select it and press the delete key.

**Comment by PeterGeelen** [comment]
Ok, thx for the helpful hint!

This dummy won't forget it ... forever ;)

I just found out from the closed issue list, this is nr 1 FAQ...
