### ISSUE TITLE
Incoming calls on profile 1 hangs up ongoing calls on profile 2

### ISSUE THREAD

**Issue by nc-chra** [TonCunha/multi-microsoft-teams#30]
Hi

I really like the idea of being able to run multiple microsoft teams profiles at the same time, however, I have encountered a small issue with multi-microsoft-teams. 
When I'm on a call on profile 1 and someone calls me up on profile 2, the call on profile automatically hangs up. Even if i'm in meetings which is very unfortunate. Any ideas for resolving this issue?

**Comment by TonCunha** [comment]
Hi @nc-chra, thanks and I'm really happy to hear you like MMT.
Unfortunately this is because Microsoft Teams has limitations in managing these features across multiple instances. MMT only supports opening multiple instances and cannot change these native Microsoft Teams behaviors.
