### ISSUE TITLE
Executable is not opening after making 3 profiles (and trying to add a 4th)

### ISSUE THREAD

**Issue by formadelfo** [TonCunha/multi-microsoft-teams#31]
Worked fine. Made 3 profiles. Now when in try to open the Multi MS Teams executable it's just not opening. Any idea how to fix? Also can't undo making the 3 profiles like this...

**Comment by TonCunha** [comment]
Hi @formadelfo 

Please try one of these:
- Check that MMT is running in the tray next to the clock. If it's running, try clicking to open MMT.
- Open Task Manager, make sure MMT is running. If it is running, try to end the task. Now try to open MMT again.
- If none of these work, you can delete the profiles and try downloading the latest version of MMT again.
Profiles are in the folder:
C:\Users\YOURUSER\AppData\Local\Microsoft\Teams\CustomProfiles

Hope this helps you.
Regards

**Comment by formadelfo** [comment]
Oh sorry, didn't knew that the app goes to the tray. :-) Maybe a good idea to put it in the readme.
Thanks!
At first look this seems to be what a lot of people need these days of working from home.
