### ISSUE TITLE
Cannot delete any profiles

### ISSUE THREAD

**Issue by yodamin** [TonCunha/multi-microsoft-teams#33]
Hi,

I have local admin access on my own corporate domain joined PC.
I am using multi teams for two corporate teams accounts.

I am trying to delete all the multi-teams profiles in order to start over.
I received a delete profile prompt when pressing D on the keyboard two or three times - clicking OK on these prompts did NOT result in the profiles being deleted.
I was going to delete the profiles manually but no hint of any multi-teams settings/profiles can be found in %appdata% or %programdata% or program install directory (I copied to %appdata%\roaming and unzipped it in there)
Add/remove programs does not reveal the program so cannot uninstall in this way
I searched the registry for Multi MS Team* and found nothing except the MUICache where I copied pasted the files to unzip (app\data) and a few more instances like this-no actual multi-teams entry in the registry where it would point to a profiles folder/file/reg entries or anything like that

I deleted the whole multi-team directory from the file system and downloaded the zip once more and unzipped it to a different location than I did the first time, ran it from the different location and when it opened all my older profiles, the ones I am trying to get rid of are STILL there?

Where are the profiles stored so I can manually delete them to remove as the Delete function within the program is not working for me?

Thanks a bunch!

John

**Comment by TonCunha** [comment]
Hi @yodamin 

Multi MS Teams runs without being installed, so there is no uninstaller.
To remove profiles, follow these steps:

1- Close all instances of Microsoft Teams.
2- Close Multi MS Teams.
3- Access the path "C:\Users\YOURUSER\AppData\Local\Microsoft\Teams"
4- Delete the "CustomProfiles" folder (this is safe, this folder was created by Multi MS Teams).

Open Multi MS Teams again. No profiles should be displayed.

Thanks.

**Comment by yodamin** [comment]
Hello,

I hope your day is going well.

Thank you very much for those steps.

Thank You and Kindest Regards,
John Fougere| Desk Side Support | Compugen Inc.
Cell:  613-868-7303

ITbuzz.ca | green4good.ca
[http://cportal.ad.int/sites/HelpDesk/_layouts/GetImage.ashx?d=F4afeb62924a04dae9c05107b16250aa9m8e55b6b5e794465fbf16794691ab2c06m10a7ed221fb54e9a8f4ff363451f6656m&ObjectDataBlobId=%7bfc225385-6e7d-4f4f-96f5-548d56e6776c%7d%7b1%7d]
***@***.***
  - Simplifying the business of technology…together
Compugen e-mail transmission
