### ISSUE TITLE
Not working - See screenshot

### ISSUE THREAD

**Issue by DoKnocK** [TonCunha/multi-microsoft-teams#35]
**Error** - must install .NET Core, pressing Yes (doesn't do anything).
Anyhow, I did try with both .NET 7.0 & 6.0 - this just doesn't seem to work.

Any idea anyone ? I'm having a lot of issues working with multiple clients and not having the ability to login to multiple account in teams.
Please help!

@TonCunha Cleriton, please confirm if am doing anything wrong ? Or should I install some different version of .NET Core ?

![image](https://user-images.githubusercontent.com/68970953/216430423-cb6d6810-9afe-445c-a50c-a2a0f26953a4.png)

**Comment by TonCunha** [comment]
Hi @DoKnocK 
Please, look this issue to solve this problem.
[Link Issue 34](https://github.com/TonCunha/multi-microsoft-teams/issues/34)

Regards,
Cleriton Cunha
