### ISSUE TITLE
Does not start, requests .NET Core

### ISSUE THREAD

**Issue by thomas19999999** [TonCunha/multi-microsoft-teams#36]
![image](https://user-images.githubusercontent.com/127020658/222955076-3042f585-7ce9-44b5-9996-821e8ff737c8.png)

Guys, I have issues starting the application. I have installed the latest version of .NET 7.xxxx, restarted my computer etc. 
The message stays, "yes" or "no" sdoes not make a difference.

Any ideas?

Thanks
Thomas

**Comment by thomas19999999** [comment]
ah, it's Windows 11 Enterprise, if this helps...

**Comment by TonCunha** [comment]
Hi @thomas19999999 
Please, look this issue to solve this problem.
https://github.com/TonCunha/multi-microsoft-teams/issues/34

ps: Next MMT version I'll update the .NET Core version

Regards,
Cleriton Cunha

**Comment by thomas19999999** [comment]
Thank you! Did no see this issue, sorry ;-)
