### ISSUE TITLE
Manage start by email link

### ISSUE THREAD

**Issue by bnk-ooz** [TonCunha/multi-microsoft-teams#4]
Complements for your great tool. I use it every day.

I run into one problem: when a invitation for a meeting is send by email, MMS often picks the wrong account.
How do I manage MMS to pick the right team when starting a meeting via an email link?

**Comment by TonCunha** [comment]
Hi @bnk-ooz,
Cool, I appreciate it.

Unfortunately, this is a limitation. Microsoft Teams manages this, and since it doesn't know how to handle multiple instances, it usually chooses the latter.

Regards
