### ISSUE TITLE
Problem with teams PSTN calling when using multiple profiles

### ISSUE THREAD

**Issue by alex8654** [TonCunha/multi-microsoft-teams#5]
When using a callto link, the original Teams profile is launched for calls. It doesn't try to use the profiles loaded by your tool. That means if I have 2 profiles launched in your tool, let's say profile #1 and profile #2, (profile #1 being a copy of my regular profile already setup in Teams before) it will start my original profile as a 3rd instance of teams and make the phone call over there, instead of any of the profiles opened via your launcher.

**Comment by alex8654** [comment]
I think the first profile launched get the PSTN calling preference, I'm going to test this on a VM to replicate exactly what is the behaviour.

**Comment by alex8654** [comment]
> I think the first profile launched get the PSTN calling preference, I'm going to test this on a VM to replicate exactly what is the behaviour.

never mind that, it doesn't invoke any of the created profiles in your tool, it always invoke the original profile. If I have my original profile logged out, it will ask to log in if I try to dial a number.

My work around is to use my profile as it is, and use the tool to launch 1 additional profile.

**Comment by TonCunha** [comment]
Hi @alexbleicker,
Cool, I appreciate your efforts.

Unfortunately, this is a limitation. Microsoft Teams manages this, and since it doesn't know how to handle multiple instances, it usually chooses the original.

Regards
