### ISSUE TITLE
If Teams is uninstalled and reinstalled the profile tool stops working

### ISSUE THREAD

**Issue by alex8654** [TonCunha/multi-microsoft-teams#7]
If I uninstall teams and reinstall it, the profile tool stops working and there is no way to configure it any longer. Believe we should have a way to clear it settings and start over again

**Comment by TonCunha** [comment]
@alexbleicker 
Multi Teams is not responsible for files created from Microsoft Teams. Multi Teams is just an intermediary and the responsibility for maintaining the integrity of the files lies with Microsoft Teams. In case of any problem, after uninstalling Microsoft Teams, access the folder "C:\Users\YOURUSER\AppData\Local\Microsoft\Teams" and delete the remaining files. After reinstalling Microsoft Teams, there will be no problem.
