### ISSUE TITLE
New Teams update seems to have broken mult teams

### ISSUE THREAD

**Issue by smartdecisions** [TonCunha/multi-microsoft-teams#9]
Hiya,

i got a new update on teams and it seems to have broken multi teams now my teams all just open with the same account.

Even if I create a new profile it just opens with the existing account... Version installed is 1.4.0.0.2879 (64-bit)

Cheers

**Comment by TonCunha** [comment]
Hi @smartdecisions,
The latest version is 1.0.3 and you can download it [here](https://github.com/TonCunha/multi-microsoft-teams/releases/tag/1.0.0.3). I recommend deleting all profiles, select each profile and press the delete key. Then create again, as you need.
